name: replicate
version: 1.0.0
description: A community-maintained Dart client package for Replicate.com, this package let you interact with Replicate.com APIs and create predictions from the available machine learning models.
repository: https://github.com/anasfik/replicate

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  path: ^1.8.3
  http: ^0.13.5
  meta: ^1.9.0
  collection: ^1.17.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
