name: replicate
description: A Dart client for Replicate.
version: 0.2.0

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  http: 0.13.5
  meta: 1.9.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
